// Generated by scripts/sync-ledger.mjs. Do not edit manually.
export const LEDGER_ISSUED_NUMBERS = [10404, 11188, 11327, 13333, 14222] as const;
export const LEDGER_SOURCE = "01_CONSTRUCTION-des-ONTOLOGIES/Taxonomy_Numbering_Ledger/CORE_TaxonomyNumberingLedger_v01.txt" as const;
export const LEDGER_SOURCE_MODIFIED_AT = "2026-08-14T07:32:04.667Z" as const;
