import { readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  CANONICAL_LEDGER_RELATIVE_PATH,
  resolveArchiveConfig,
} from "./archive-config.mjs";

const projectRoot = fileURLToPath(new URL("..", import.meta.url));
export const GENERATED_LEDGER_OUTPUT_PATH = path.join(projectRoot, "app", "generated-ledger.ts");

function assertOutputOutsideArchive(archiveRoot, outputPath) {
  const resolvedArchiveRoot = path.resolve(archiveRoot);
  const resolvedOutputPath = path.resolve(outputPath);
  const relativeOutputPath = path.relative(resolvedArchiveRoot, resolvedOutputPath);
  const isInsideArchive =
    relativeOutputPath === "" ||
    (!path.isAbsolute(relativeOutputPath) &&
      relativeOutputPath !== ".." &&
      !relativeOutputPath.startsWith(`..${path.sep}`));

  if (isInsideArchive) {
    throw new Error(
      `Refusing to write generated ledger data to ${resolvedOutputPath}: UNCLES_ARCHIVE_ROOT is a read-only archive at ${resolvedArchiveRoot}, and output paths must not equal or descend from it.`,
    );
  }

  return resolvedOutputPath;
}

export function parseIssuedNumbers(ledger) {
  return Array.from(
    new Set(Array.from(ledger.matchAll(/^\|\s*(1\d{4})\s*\|/gm), (match) => Number(match[1]))),
  ).sort((left, right) => left - right);
}

export function renderGeneratedLedger(issuedNumbers, modifiedAt) {
  return `// Generated by scripts/sync-ledger.mjs. Do not edit manually.
export const LEDGER_ISSUED_NUMBERS = [${issuedNumbers.join(", ")}] as const;
export const LEDGER_SOURCE = ${JSON.stringify(CANONICAL_LEDGER_RELATIVE_PATH)} as const;
export const LEDGER_SOURCE_MODIFIED_AT = ${JSON.stringify(modifiedAt)} as const;
`;
}

export async function synchronizeLedger({
  env = process.env,
  outputPath = GENERATED_LEDGER_OUTPUT_PATH,
  checkOnly = false,
} = {}) {
  const { archiveRoot, ledgerPath } = await resolveArchiveConfig(env);
  const resolvedOutputPath = assertOutputOutsideArchive(archiveRoot, outputPath);
  let ledger;
  let ledgerStat;

  try {
    [ledger, ledgerStat] = await Promise.all([
      readFile(ledgerPath, "utf8"),
      stat(ledgerPath),
    ]);
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    throw new Error(`Cannot read the canonical Taxonomy Numbering Ledger at ${ledgerPath}: ${detail}`);
  }

  const issuedNumbers = parseIssuedNumbers(ledger);
  if (issuedNumbers.length === 0) {
    throw new Error(`Cannot synchronize the canonical Taxonomy Numbering Ledger: no valid 1#### register rows were found in ${ledgerPath}`);
  }

  const generatedSource = renderGeneratedLedger(issuedNumbers, ledgerStat.mtime.toISOString());
  let currentSource = "";

  try {
    currentSource = await readFile(resolvedOutputPath, "utf8");
  } catch {
    // Synchronization may create the generated module; verification remains fail-closed below.
  }

  if (checkOnly && currentSource !== generatedSource) {
    throw new Error(`Generated ledger data is out of date at ${resolvedOutputPath}. Run npm run sync-ledger with UNCLES_ARCHIVE_ROOT configured, then review and commit the regenerated file.`);
  }

  if (!checkOnly && currentSource !== generatedSource) {
    await writeFile(resolvedOutputPath, generatedSource, "utf8");
  }

  return { changed: currentSource !== generatedSource, issuedNumbers, ledgerPath, outputPath: resolvedOutputPath };
}

function parseArguments(args) {
  let checkOnly = false;

  for (const argument of args) {
    if (argument === "--check") {
      checkOnly = true;
    } else {
      throw new Error(`Unknown ledger synchronization argument: ${argument}`);
    }
  }

  return { checkOnly };
}

async function main() {
  const options = parseArguments(process.argv.slice(2));
  const result = await synchronizeLedger(options);
  const action = options.checkOnly ? "Verified" : result.changed ? "Synchronized" : "Confirmed";
  console.log(`${action} ${result.issuedNumbers.length} unavailable number${result.issuedNumbers.length === 1 ? "" : "s"} from the canonical Taxonomy Numbering Ledger.`);
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  try {
    await main();
  } catch (error) {
    const detail = error instanceof Error ? error.message : String(error);
    console.error(`Ledger synchronization failed.\n${detail}`);
    process.exitCode = 1;
  }
}
